config/routes.rb
Rails.application.routes.draw do

root "mainpg#index"
resources :cancers do
  collection {post :import}
end
resources :diseases do
  collection {post :import}
end

resources :mutations
resources :users
resources :genes

post "/cancers(.:format)" => "cancers#acs_cancer_list"

get "signin" => "authentication#new"
post "signin" => "authentication#create"
get "signout" => "authentication#destroy"
get "signup" => 'registrations#new'
post "signup" => 'registrations#create'

end

app/models/cancer.rb
class Cancer < ActiveRecord::Base

 has_many :diseases, through: :mutations


  def self.import(file)
    CSV.foreach(file.path, headers: true) do |row|
      Cancer.create! row.to_hash
    end
  end

end

app/controllers/cancers_controller.rb
class CancersController < ApplicationController

  def index
    @cut_off = 1
    @mutation_list = Mutation.order(:original_histology).select(:original_histology).uniq
    @mutation_test = Mutation.pluck(:original_histology).uniq.sort.reverse
    @mutation_test = @mutation_test.push("Select tumour type...").reverse
    @mut_table = Mutation.where("mutation_counter >= ?", @cut_off).pluck(:consensus_cancer_gene_id).uniq
    @mut_cnt = @mut_table.count
    if params[:search].present?
      @consensus_cancer_genes = ConsensusCancerGene.where("gene_symbol like ? OR name like ?",
      "%#{ params[:search] }%", "%#{ params[:search] }%").order(params[:gene_symbol])

      @consensus_genes_count = @consensus_cancer_genes.count
    elsif params[:original_histology] == "Select tumour type..."
      @consensus_cancer_genes = ConsensusCancerGene.where(id: @mut_table).order(params[:gene_symbol])
      @consensus_genes_count = ConsensusCancerGene.order(params[:gene_symbol]).count
    elsif params[:original_histology].present?
      @mutation_selector = Mutation.where(original_histology: params[:original_histology]).order(params[:gene_symbol])
      @holding = @mutation_selector.pluck(:consensus_cancer_gene_id).sort.uniq
      @consensus_cancer_genes = ConsensusCancerGene.where(id: @holding).order(params[:gene_symbol])
      @consensus_genes_count = @holding.count
    else
      @consensus_cancer_genes = ConsensusCancerGene.where(id: @mut_table).order(params[:gene_symbol])
      @consensus_genes_count = ConsensusCancerGene.order(params[:gene_symbol]).count
    end
  end

  def new
    @cancer = Cancer.new
  end

  def edit
    @cancer =Cancer.find(params[:id])
  end

  def count_somatic
    @som_count = 0
      if @consensus_cancer_gene.somatic == "false"
        @som_count += 1
      else
      end
  end

  def show
    if current_user
      @current_user = User.find(current_user.id)
      @current_gene_array = @current_user.my_genes
    end
    @consensus_cancer_gene = ConsensusCancerGene.find(params[:id])
    @all_gene_mutations = Mutation.where(consensus_cancer_gene_id: @consensus_cancer_gene.id).pluck(:original_histology).uniq
    @new_hist_array = []
    @all_gene_mutations.each do |gene|
      gene = gene.gsub(/_/, " ")
      @new_hist_array.push(gene)
    end
    @histology_list =@new_hist_array.join(", ")
    @final_hist = @new_hist_array.join(", ")
    if params[:mutation_cut_off].present?
      @cut_off = params[:mutation_cut_off]
    else
      @cut_off = 1
    end
    @diseases = Disease.where(gene_name: @consensus_cancer_gene.gene_symbol)
    @mutation_count = Disease.where(gene_name: @consensus_cancer_gene.gene_symbol).count
    @uniq_mutation_count = Disease.where(gene_name: @consensus_cancer_gene.gene_symbol).select(:cds_mutation_syntax).map(&:cds_mutation_syntax).uniq.count
    @mutties_not_zero = @consensus_cancer_gene.mutations.where.not(nuc_position1: 0)
    @mutties_not_zero = @mutties_not_zero.where.not(nuc_position1: -100)
    @mutties_not_zero = @mutties_not_zero.where.not(nuc_change_from: nil)
    count_somatic
    @mutties = @mutties_not_zero.order('nuc_position1').where("mutation_counter >= ?", @cut_off)
    @mutties_json = @mutties.to_json
    @mutties_counter = @mutties.count
    @json_mutations = @mutties_not_zero
    @page_mutties = @mutties.where.not(nuc_position1: 0).page params[:page]
    @uniq_array = @mutties.map(&:original_mutation_string).uniq
  end

  def acs_cancer_list
  end


  def create
    Cancer.delete_all
    @disease_master = CSV.read('acs_cancers.csv')
    @disease = @disease_master[0]
    @disease = @disease[0..10]
    @disease.each do |disease|
      @cancer = Cancer.new(cancer_params)
      disease = disease.capitalize
      cancer_page = Wikipedia.find( "#{disease}" )
      cancer_name_raw = cancer_page.title
      cancer_name = cancer_name_raw.gsub(/ /, "_")
      @cancer[:name] = cancer_name_raw
      @cancer[:search_name] = cancer_name
      gene_page = Wikipedia.find("#{disease}")
      gene_name_raw = gene_page.title
      gene_name = gene_name_raw.gsub(/ /, "_")
      @cancer[:genes] = gene_name_raw
      @cancer[:gene_search_name] = gene_name
      @cancer.save
   end
      # cname = @cancer.name.capitalize
      # redirect_to cancers_path, notice: "Cancer: #{cname} - was added to the database."
    # else
      # render :new
    # end
    redirect_to cancers_path
  end

  def update
    @cancer = Cancer.find(params[:id])
    cancer_page = Wikipedia.find( "#{@cancer.name}" )
    cancer_name_raw = cancer_page.title
    cancer_name = cancer_name_raw.gsub(/ /, "_")
    @cancer[:name] = cancer_name_raw
    @cancer[:search_name] = cancer_name
    gene_page = Wikipedia.find("#{@cancer.genes}")
    gene_name_raw = gene_page.title
    gene_name = gene_name_raw.gsub(/ /, "_")
    @cancer[:genes] = gene_name_raw
    @cancer[:gene_search_name] = gene_name
    if @cancer.update(cancer_params)
      cname = @cancer.name.capitalize
      redirect_to @cancer, notice: "Cancer: #{cname} - was updated."
    else
      render :edit
    end
  end

  def destroy
    @cancer = Cancer.find(parms[:id])
    cname = @cancer.name.capitalize
    @cancer.destroy
    redirect_to cancers_path, notice: "Cancer: #{cname} - was deleted from the database"
  end

  private

  def cancer_params
    params.require(:cancer).permit(:name, :genes, :search_name, :gene_search_name)
  end

  # def mutation_params
  #  params.require(:mutation).permit(:consensus_cancer_gene_id, :disease_id)
  # end
end

app/views/cancers/_form.html.erb
<%= form_for(@cancer, {class: "form-horizontal center"}) do |f| %>

    <% if f.object.errors.any? %>
      <ul class="errors">
        <% f.object.errors.full_messages.each do |error| %>
          <li><%= error %></li>
        <% end %>
      </ul>
    <% end %>

  <div class="form-group">
    <%= f.label :name, class: "control-label" %>
    <%= f.text_field :name, class: "form-control"%>
  </div>


  <div class="form-group">
    <%= f.label :genes, class: "control-label" %>
    <%= f.text_field :genes, class: "form-control"%>
  </div>

  <div class="form-group">
    <%= f.submit class: 'btn btn-primary'%>
  </div>

<% end %>

app/views/cancers/edit.html.erb
<% if notice != nil %>
  <div class="alert alert-danger">
    <%= notice %>
</div>
<% end %>
<div class="well col-md-4 col-md-offset-4">
  <h1>Edit Cancer</h1>
  <%= render "form" %>
</div>

app/views/cancers/index.html.erb
<% if notice != nil %>
  <div class="alert alert-danger cancer-index-notice">
    <%= notice %>
</div>
<% end %>
<div>
  <% if (params[:search] == nil || params[:search] == "") && (params[:original_histology] == nil || params[:original_histology] == "")%>
    <h2 class="header-normalizer"><%= "List of #{@consensus_genes_count} known genes involved in human cancers."%></h2>
  <% elsif  (params[:search] == nil || params[:search] == "")%>
    <h2 class="header-normalizer"><%= "#{params[:original_histology].capitalize} associated genes"%></h2>
  <% else %>
  <h2 class="header-normalizer"><%= "Genes associated with your search."%></h2>

  <% end %>
</div>
<br>
<div>
</div>
<div class="clearfix columns manual-table-header">
  <div>

        <span class="shift-back">
          <% if (params[:search] == nil || params[:search] == "") && (params[:original_histology] == nil || params[:original_histology] == "")%>
            <%= "All #{@consensus_genes_count} genes currently showing." %>
            <% else %>
        <%=ActionController::Base.helpers.pluralize(@consensus_genes_count, 'gene')%>
        <%="found in your search."%>
        <% end %>
        </span>
  </div>
  <div class="two-column column ">
  <%= form_tag cancers_path, :method => 'get' do %>
   <p>
    <%= text_field_tag :search, params[:search], class: "search-float" %>
    <%= submit_tag "Search", name: nil, class: "search-form"%>
   </p>
   <% end %>
 </div>
  <div class="six-column column pulldown-format">
  <%=form_tag({ :action => "index"}, { :method => "get" }) do %>
    <% @fillers = "Select tumour type...."%>
    <%=select_tag(:original_histology,
                  options_for_select(@mutation_test, params[:original_histology]),
                  {:select => "Select tumour type...", class: "search-float", :data => {behavior: "autosubmit"}} )%>

  <% end %>
  </div>

</div>
<div class="manual-table columns">
  <table>
    <thead>
     <tr>
     </tr>
    </thead>
    <tbody>
     <% @consensus_cancer_genes.sort.each do |cancer_genes| %>
     <%= button_to "#{cancer_genes.gene_symbol}", cancer_path(cancer_genes), class: "cancer-entry marginalize", method: :get %>
       <% end %>
    </tbody>
  </table>
</div>
<div class='filler'>

</div>

app/views/cancers/new.html.erb
<div class="container">
  <div class="well col-md-3 col-md-offset-1 csvform">
    <h4> CSV import<h4>
    <% if notice != nil %>
      <div class="alert alert-danger">
        <%= notice %>
      </div>
    <% end %>
  <%= form_tag import_cancers_path, multipart: true do %>
    <%= file_field_tag :file, class: "form-control" %>
    <br>
    <%= submit_tag "Import COSMIC CSV" %>
  <%end%>
  </div>
</div>

app/views/cancers/show.html.erb
<% if notice != nil %>
  <div class="alert alert-danger">
    <%= notice %>
</div>
<% end %>
<h2 class="gene-header"><%=" #{@consensus_cancer_gene.gene_symbol} - #{@consensus_cancer_gene.name.capitalize}"%></h2>
  <div class="mutation_container clearfix">
    <div class="single_mutation_data">
        <div class="inner-container">
            <article class='single-gene-details clearfix'>
                <section class="column show-column first">
                    <% if current_user %>
                    <%@current_gene_array.push(@consensus_cancer_gene.id) %>
                    <%@current_gene_array = @current_gene_array.uniq%>
                    <span><%=button_to "Add gene",
                  { :controller=>'users', :action=>'update',
                    'user'=>{:my_genes=>@current_gene_array}, :id=>current_user.id },
                    class: "link-format adjustable add-gene", :method => :patch %>
                    <% end %></span>

                    <%= button_to "NCBI: #{@consensus_cancer_gene.gene_symbol}",
                    "http://www.ncbi.nlm.nih.gov/gene/#{@consensus_cancer_gene.entrez_geneid}",
                    class: "link-format adjustable", method: :get %>

                  <p>Mutations: <%= @mutties_not_zero.count %></p>


                </section>
                <section class="column show-column">
                  <% if @consensus_cancer_gene.somatic == nil %>
                    <p>Somatic:<%= " No" %></p>
                  <% else %>
                    <p>Somatic:<%= " #{@consensus_cancer_gene.somatic.capitalize}" %></p>
                  <% end %>
                  <% if @consensus_cancer_gene.germline == nil %>
                    <p>Germline:<%= " No" %></p>
                  <% else %>
                    <p>Germline:<%= " #{@consensus_cancer_gene.germline}" %></p>
                  <% end %>
                </section>
                <section class="column show-column tummie-media">
                  <p class="highlights" >Associated tumours: <%= @new_hist_array.count  %></p>
                  <p>
                    <%=@histology_list%>
                  </p>
                </section>
              </article>
              <div class="tummie-list">
              <article class="single-gene-details clearfix">
                <section>
                    <p class="highlights" >Associated tumours: <%= @new_hist_array.count  %></p>
                    <ol>
                    <%@new_hist_array.each do |tumuor|%>
                      <li><%= tumuor.capitalize %></li>
                    <% end %>
                    </ol>
                </section>
            </article>
          </div>
        </div>
    </div>
    <article class="columns clearfix shift">
        <span class="cuttoffCounter">
          <%=form_tag({ :action => "show"}, { :method => "get"}) do %>
            <%=select_tag(:mutation_cut_off, options_for_select([1,2,5,10,50,100,500,1000], params[:mutation_cut_off]),
            {:include_blank => true, class: "search-float",  data: {behavior: "autosubmit"}} )%>
          <% end %>
        </span>
      <section class="title-center">
        <%="#{@mutties_counter} mutations (Hit rate: #{@cut_off})"%>
      </section>

        <br>
      <section class="column column-two media-change">
        <p>Type:<span class="push-right" id="mtype"></span></p>
        <p>cDNA pos:<span class="push-right" id="initial_position"> </span></p>
        <p>Seq count:<span class="push-right" id="mutation_count"> X</span> </p>
      </section>
      <section class="column">
        <p>Hit rate:<span class="push-right"><%="#{@cut_off}"%></span></p>
        <p>WT nt:<span class="push-right" id="wtype"></span></p>
        <p>Mutant nt:<span class="push-right" id="specific_mutation"> </span></p>
      </section>
    </article>
    <div class="mutation_graph"></div>
  </div>

<% content_for(:js) do %>
  <script>
    $(function () {
      SingleGeneGraph.init(<%= @mutties_json.html_safe %>);
    });
  </script>
<% end %>