config/routes.rb
Rails.application.routes.draw do

root "mainpg#index"
resources :cancers do
  collection {post :import}
end
resources :diseases do
  collection {post :import}
end

resources :mutations
resources :users
resources :genes

post "/cancers(.:format)" => "cancers#acs_cancer_list"

get "signin" => "authentication#new"
post "signin" => "authentication#create"
get "signout" => "authentication#destroy"
get "signup" => 'registrations#new'
post "signup" => 'registrations#create'

end

app/views/layouts/_nav_login.html.erb
<%= form_for :authy, url: signin_path do |f| %>
  <div>
    <% if signup_path %>
      <%= f.label :email%>
      <%= f.email_field :email%>
      <%= f.label :password%>
      <%= f.password_field :password %>
      <%= f.submit "Login" %>
      <span class="signup-adjust"><%= link_to"Sign Up", signup_path %></span>
      <% end %>
  </div>
  <% if @sign_in_error %>
      <p class="error-format"><%= @sign_in_error %></p>
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= favicon_link_tag '46LYRs.jpg'%>
    <title>BigBangGenetics</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag 'application', media: 'all'%>
    <%= javascript_include_tag 'application'%>
  </head>
  <div>
</div>

<body>
<div class="navbar columns">
  <div class="container ">
    <div class="column column-eight ">
      <%= link_to("BBGenetics", root_path) %>
    </div>
      <% if current_user %>
      <span class="nav-right">
        Welcome <%= current_user.first_name%>!
      <div class="column column-two signs">
        <%= link_to "Sign Out", signout_path %>
      </div>
      </span>
      <% else  %>
      <div class="nav-right column-four">
        <%= render "layouts/nav_login" unless @reg == "reg"  %>
      </div>
      <% end %>
  </div>
</div>

    <div class="container">
      <%= yield %>
    </div>
      <footer>
        <div class="footbar columns">
          <div class="column column-two">
            <%= link_to("Home", root_path) %> |
            <%= link_to("Cancers", cancers_path) %>
          </div>
        </div>
      </footer>
      <%= content_for(:js) %>
  </body>
</html>

app/views/layouts/new.html.erb
<div class="well col-md-5 col-md-offset-3">
<%= form_for(@user, url: signup_path) do |f| %>
  <h1>Register</h1>

  <% if f.object.errors.any? %>
    <ul class="errors">
      <% f.object.errors.full_messages.each do |error| %>
        <li><%= error %></li>
      <% end %>
    </ul>
  <% end %>

  <div class="form-group">
    <%= f.label :first_name, class: "control-label"%>
    <%= f.text_field :first_name, autofocus: true, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :last_name, class: "control-label" %>
    <%= f.text_field :last_name, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :age, class: "control-label" %>
    <%= f.number_field :age, class: "form-control"%>
  </div class="form-group">

  <div class="form-group">
    <%= f.label :email, class: "control-label" %>
    <%= f.email_field :email, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :password, class: "control-label" %>
    <%= f.password_field :password, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :password_confirmation, "Confirm", class: "control-label" %>
    <%= f.password_field :password_confirmation, class: "form-control" %>
  </div>

  <div>
    <%= f.submit "Register" %>
  </div>
<% end %>
</div>
<div class="whitespace">

</div>